version: '3.8'

services:
  frontend:
    build: .
    image: frontend
    container_name: webalgoshits-frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: 
      context: ./neural_network/backend
      dockerfile: Dockerfile
    image: backend
    container_name: webalgoshits-backend
    ports:
      - "5000:80"
    volumes:
      - ./neural_network/backend:/app